name: SimpleGroupChat
version: '1.0-SNAPSHOT'
main: kz.megabob.simpleGroupChat.SimpleGroupChat
api-version: '1.21'
authors: [ megabob ]
description: Плагин группового чата с кастомными форматами
softdepend: [PlaceholderAPI]
commands:
  gcreate:
    description: Создать группу
  glist:
    description: Показать все группы
  grequest:
    description: Подать заявку в группу
  gacceptrequest:
    description: Принять игрока
  gacceptinvite:
    description: Принять приглашение в группу
  gdenyrequest:
    description: Отклонить заявку
  gdenyinvite:
    description: Отклонить приглашение
  gkick:
    description: Кикнуть из группы
  ginvite:
    description: Пригласить игрока в группу
  ginvites:
    description: Показать приглашения
  gleave:
    description: Покинуть группу
  grequests:
    description: Показать заявки
  gchat:
    description: Управление групповым чатом
    usage: /gchat on|off|status
    aliases: [gc]


